# Generated by Django 4.2.2 on 2023-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
